// <auto-generated />
using System;
using Assignment_AI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Assignment_AI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Assignment_AI.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 5000m,
                            Balance = 0m,
                            Date = new DateTime(2024, 2, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Initial Office Credit",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500m,
                            Balance = 0m,
                            Date = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Snacks Party",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 285m,
                            Balance = 0m,
                            Date = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Printing Sheets",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 3000m,
                            Balance = 0m,
                            Date = new DateTime(2024, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Misc. Expense",
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
